# -*- coding: utf-8 -*-
"""trial1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15aHFs51PLIQtttTsqlwvll8pX-YECV9R
"""

a="this is my first backup"
print(a)